<script type="text/javascript">
$(function() {
	if($.bbq.getState('registered')=='justnow') {
		$.bbq.removeState('registered');
		$('#messages').append($('<div>').addClass('message success hidden').text('Welcome to the Library! Please use your email address and password to login below'));
		$('#messages .message').slideDown('fast');
		hideMessages();
	}
});
</script>
<div id="register" class="page">
	<?php echo $this->form; ?>
</div>