<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Zend Framework - Library</title>
<?php
echo $this->headLink()
	->appendStylesheet('/css/html5reset-1.6.1.css')
	->appendStylesheet('/css/common.css')
	->appendStylesheet('/css/global.css');
echo $this->jQuery();
echo $this->headScript()
	->appendFile('/js/global.js');
?>
</head>
<body>
<div id="header">
	<div id="title">
		Welcome To The <strike>Jungle</strike> Library<?php if($this->user) echo ', '.$this->escape($this->user->getField('forename')).' ('.$this->escape($this->user->getReferenced('Usertypes')->getField('name')).')!'; ?>
	</div>
	<div id="navigation" class="group">
		<ul>
			<li>
				<a href="/">Home</a>
			</li>
<?php if($this->user): ?>
			<li>
				<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'library'), 'default', true); ?>">Library</a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'logout'), 'default', true); ?>">Logout</a>
			</li>
<?php else: ?>
			<li>
				<a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'register'), 'default', true); ?>">Register</a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'login'), 'default', true); ?>">Login</a>
			</li>
<?php endif ?>
		</ul>
	</div>
</div>
<div id="messages">
	<?php if($this->success): ?>
	<div class="message success">
		<?php echo $this->success; ?>
	</div>
	<?php endif ?>
	<?php if($this->alert): ?>
	<div class="message alert">
		<?php echo $this->alert; ?>
	</div>
	<?php endif ?>
	<?php if($this->error): ?>
	<div class="message error">
		<?php echo $this->error; ?>
	</div>
	<?php endif ?>
</div>

<?php echo $this->layout()->content; ?>

</body>
</html>